#+title: Mexico Trip - Part 2 CDMX
#+author: bagnaram
#+DATE: 2022-08-09
#+lastmod: [2022-08-09 Tue 12:37]
#+categories[]: travel mexico cdmx agave mezcal
#+draft: false
* Arrival in CDMX
My first day in CDMX was with our group and we planned a breakfast and a time to
explore a mercado called Mercado de Artisinal. We were staying in the Condesa
area near Chapultepec, which seems to be more of a classy part of the city but
it is divided by large boulevards with nice trees and paths. My friends and I
were headed towards El Centro, where the Artisinal market was. We would stop for
breakfast somewhere along the way. After journeying for a little while we
stumbled into a very home-like restaurant called Restaurant Meson Del Kajon.
This breakfast was a traditional meal of bread(pan) and various topping. I had
the huevos & mole and it was a nice hearty breakfast meal!

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/ps1A2PqwgezjkzX68"><img
src="https://lh3.googleusercontent.com/pw/AL9nZEX3nQWZspMytiKwVo6dl7Fdm2P342LHhxRuxmtojf1F1NFCDHcffkHFYDDJyqwp356C6lYzl8eOUnfBDr0Cq99oJzHVa6YwvxauTbHxiH382kOVioW8u4wwOx4iDTkSwrtyMcTiWbBEG6JtIPyEzYH2=w1170-h877-no?authuser=0"
alt="Huevos" class="inline"/></a>
#+END_EXPORT

After the meal we walked through the Artisinal Market. This place is a vast
marketplace with small vendors selling everything from pottery, to trinkets and
dishes. We split off and each of us explored the mercado. At this point it
started raining very hard and I wanted to pick out some house numbers made of
ceramic tile. these type of house numbers are famous and are a nice touch to add
onto your building. With the rain pouring harder, we decided to leave and head
back to our accommodation. At this juncture, I walked back and stopped in a nice
panaderia I found along the way back.

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/VXRPLGZdUBvwunj59"><img
src="https://lh3.googleusercontent.com/HWP2OU85oysQVNnP3YQRox7qK3QV3NjbHVgxtLCYXz0ffadqlS2M-bLUWkwnKXgszl6YHIuSUVwPRzrqL8VbdCCvFm_f_7ZCjM5I3aePa3q00lqJ2r-sV3gervRKEpRNyk2fslFBviLz2Wv02SpdxwO7-b02aAk2_spzFbLncuIHD6X2tVzU2azmP-A6MpxeM6I5QYhSpJUeNL_VmsMTM7w6oSB4Tun_HCpxjakXgr6j2dSVJcxPKHFZunSqwfIYXpoqHEe4h06r6wsI8K7xSk1dohBkOjVf8vXP0e9JXGhxeROR1AKyglphcxApEVzUhKiyqODNCKIGqKRBLNrfEP5e_glKZSfEEEN4ca83mu4ZXCA6n7LyWcTK7-ILfnlUL16jMeeJc14dAvpeaPuHHudLF5i4QKAAYaflQeVZb9ZFDj2lpGPXfdQ72jhv4hs2F9OXeqPSZE0mddEFrdzltyUoZ-t_70DbnOGkVh8LUsnBDSxJ0qWTqidAkkjR2DKjyeEM0osdb20ZIdgaakPhvs03IgMjw2NnLWUrQTAIPcu4iyK0XssfUz2gbICpH47xgAQbHjcQgB9V3B_wEEskQK1ugOU03tb6-PEb0VV8yy9HW2YhuMK3kUvFdTC1Vrw-jW1DxBRb7b24JlIKFVOJwLjVci8VbwE8EO-Ua1wv-xXJneBypQb-JYyokgWtFNrykC8EqYUp77kI4HijbmPMSmo9XKnldTIFpwMCiRuiY7XLi_hLeA-CV7fx-tY=w1172-h879-no?authuser=0"
alt="Panaderia" class="inline"/></a>
#+END_EXPORT

* Teoticuan Pyramids
We started this day very early because we would be taking a tour to the ancient
pyramids near Mexico City. The tour bus would meet us at 6:30AM and we would
journey to the pyramids and take a full tour in the morning before the place
would get too busy.
#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/rayarqG6Jb939hDX8"><img
src="https://lh3.googleusercontent.com/mbhSEcCunMPEoaQaj46jGCFRqrtZy6AoTSlXGnhdyvOYVmp7qjJ6UXffDakyrz9Jh91Y1DhRYpjyBCyPWH8zzhgsW7Jf9d--nW6Mi8yrU0LqwoAhYYdhwSLLsYy6p3PzUcLMCMc0pPR86rIQ95a0l7l8eTDxLr5h4Z7sP_nLleHcjPdtRreSOWJ02VAeG6Ft4LM_6mhEXP43hfaWxX9UsczjCLYrLUoALTHJrzuf-xKv-Nw-h10jun7Dn-NKK_3aJ6YHHWCeiZ62U5saaikYx2COQyzEJwg0b8y00-ugg7InQjTlH_Y0_Mn_E2meet5lIfBcOHqAWXayTZA-Wk72-BxZS-Yrq7oejectyPpyEjeYOb_xqrUgNUKATrRE7SLhClqTJ6c8O1xVKcL9x61mdQ7mHTL4n92WIQb3K1-qQMFjdPa5cRn91U27yGyM_N3ZPlcY-kTb9hZzL6mKkTENBUbbxdp7fwIbiHjZs5d8cfPTx52f_DE7iwNZIqLAkB7i8uofOOiewyj6aM4ikoaBfKMDffkf7g5inXEyT9W1RevyDBqNxtPj_edNbfW59AD9MMM_lAscrsWIfpx01M-8C_q8XAjPqZXgTcuZYA0j8W49bPVvtg7gp8BG_NTfYEd4JmjcOgz5F_JWv1i10iWhraqdan-jiAllZKGRvT6XTEVFzLtwnTXuEdfQjZVT9VQiD2jNpGIeUEn0CrNqoYf6Quobh0Yec_RvCgqv7hV6sjNoeosMawePtDpG0-g=w1172-h879-no?authuser=0"
alt="Teoticuan" class="inline"/></a>
#+END_EXPORT

As we arrived, the morning sky was dotted with many hot-air balloons. It appears
that separate tours are available to take you up to see the pyramids from great
heights! As we unloaded and entered the park, we saw the pyramid scene for the
first time. These were built over the course of hundreds of years with varying
layers and Adonis over the years, displaying a sort of shell of pyramid layers.
They were magnificent and the Sun and Moon pyramids dominated the scene. It was
fun to imagine thousands of people walking the plazas and living in this space
as it was so peaceful to see in the morning. Shortly the crowds arrived and
changed the feel of the place. But in a good way, because it gave a bustling and
city feel to the area. As we toured these ruins, the guide explained some of the
history including the Aztecs finding this ancient civilization seemingly
abandoned. Then the Spanish entering and making their print on the place.

#+BEGIN_EXPORT html
<iframe width="100%" height="512" src="https://www.youtube.com/embed/ypFYopUzqp8" title="Pyramids" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

After the tour we had lunch at a restaurant on the grounds of the park area with
some live mexican Norteno music which made a great scene! After we finished we
reached back to CDMX and the rest of the day was open for me. My friends would
be having dinner at a chef's tasting, but I opted to free my time and try out a
famous al pastor taco place. This place was an automotive garage during the day,
and served street tacos at night. The ultimate and unlikely combination that I
had to try. It was about an hour walk from our accommodation in Candenza, and I
wanted to walk around and see some of the city as well. A nice walk later, I
found some of the most delicious al-pastor at the walk-up restaurant called El
Visito. It did not disappoint, with flavorful meat and salsas to top the tacos!

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/ZZPVrtL6VeNTz1jZA"><img
src="https://lh3.googleusercontent.com/HX4KRd19anWXUR1Uw4a8_TW3kfFio2BUkvbFG1tyXpyk1yTx1WNaA7RRjXYRpgXcD5Q4Ie4w56iHSaRZNmy203vbIXA1T6q7fjfurtBIHFuEDQhxxpMVZ0JvO3b4rfaJLMw1LTSIap3R7fwT99QL-E3g6mOVsrWLUHvDEWKbyt7qESSxuQDyS0LLXZwpkG1Zdquc5WDcnY2Gzw2A0NRfnVF6kZjcrZVQbmGNLaIzgu7H_fauO9vPNANCIRYynj8rw1hhHNtcSmoN5pT9zDhgThY14vCRpp-T_IbSXH06eQ6K6Rwmfc1_PoASx7bZLNHcntruVS4U3VxXihz2f79V8z03gRkepZOSPWVl6XkhHo3o6vD-46pGj_g6vp-9vAZbbtyGq2hHv0uzxS35SZNbHET_AZ-1U9AeZQA-JPc03_hh6VUxNbhq4cCBIGC0LPjJBfUb-WRgdDmvMLVIayY7DIXrU4ZLRvo6ASXVgH06EDdmt2fQjsKM76x2tVmwHgPMkAnkkKAJU5EV2Im44xz9juO0hyG15CmKTV9ciVazBJbGgBXuX0PFTgi8ONguCLEle9bAen8ldYfYSNq_WEyW7Rjvr4P-CnwmNW9ObTSfKzB8CGDASD3vBLIPfUbVibrS1l65OhJX8p2jdxK4Hgz37ZsrkQcnTrKnBOVtrDE_ImECp_ts_kIqMrIsKZm5uSHZS5ngpL0jd1f25MryPOoWmgXvXkQdPjr6pk7C40vgZ_2jS5-3T0NHcPF_fzE=w1172-h879-no?authuser=0"
alt="Los Mejores Al Pastor" class="inline"/></a>
#+END_EXPORT

I walked back and stopped at a nice mezcaleria called Neicos. This place was one
of my highlights. I stumbled into the place and met some incredibly nice and
hospitable folks there. What a nice place to become a regular. What appears like
a liquor store on the bottom level, a staircase leads you to a middle level
mezcal bar, and rooftop on the 3rd level. I would make this mezcaleria a regular
stop during my time in CDMX!

* Mercados
The next day my friends and I would explore Mercado Sonora in CDMX. We planned
the journey over cafe at a place nextdoor to our accommodation with a very
friendly owner. Mercado Sonora isn't the place for everyone. If you are
sensitive to animal treatment including tight spaces and cages I would skip this
one. We mainly went to this mercado to see some of the new-age and religious
items for sale. These include incense, paper masks, and an assortment of bootleg
dollar store items. As a cartoon fan, we saw many un-sanctioned Sonic the
Hedgehog merchandise that I could not resist. At this market one of my friends
experienced our closest shady moment in which she was given change from a vendor
containing a counterfeit bill. We only discovered this after she attempted to
make a purchase with one of the bills.


#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/jQaYxY7XRQxHre3v9"><img
src="https://lh3.googleusercontent.com/FW___JxUraQswQZ0AplPVIUkUcPbXNIDoVzgWUAkEqOaTbV1ujYBpI8lyO3FEoJ_hsR_M4qs10c2BTv3Xq6jf93Xsx4rB2JveraJ4QAyxfuyY9xnYLrWAefJuKkfgcCURUAst0q0f-A-r_vrJtRahJayVRa-VSkY4xVRk10Bnc9nQhRgIscBxpXVEuD121fsrMMp0HMdrfzAegxvBgnXIVpF8NubRlGtf3Fnvx8aQUC_FIAE3JZKE73oNe9taMYcNcX49wtIgWAMC5cX_CxneUdK8PHwq4fwbg6VU5Ajl-qQ_FJpxU-wIxC-62GiTGAgBJYngiGDsgckkOX-OrrgXEio9wCZ5aY6la-gnqXDBc_Lq4X8iu-lPF1czspyfgTaXgRGKNFapMIApM3fEud0L2-CSRLwZ3x8oWWOuGEhgIOt-2vdq3rKgN7bi-Z7dbUlIWoUy-IBSz6tflHWwWYi_CIzyE3FaJGsKrvfKmx-z1yufhJ39ybzNNHOMZpFywLKaNM5TJre78N1itnPawZzlmN-p8k89guQpx_wvFXpnoqnCgY07KWdfgNMiPrPQAU-Q3rOJBbgtWaxpsNChQ9t0oAfENxR-wiHUbqcGBydazl1YCg85pGlYfpVZBvPlbsCkKvGiP_Pr2u0scQsamxmt9mUYNsbBOiJcFBpo9eMOy78IAhNrJOqm-EhTUwh1X1SlcX4mMJ7o7rKKt-nns4-V29yhnKDsoiaCbm35xfM5jPpB89eu0VeNPLlEiM=w1172-h879-no?authuser=0"
alt="Sonora" class="inline"/></a>
#+END_EXPORT


After exploring Sonora, we ventured to an adjacent Mercado de la Merced that was
more of a household goods and street food market. This place was massive. If you
get a thrill of feeling lost in a seemingly endless labyrinth of marketplace
vendors in a tight space, this is the place for you! I fall into this category
and quickly went into sensory overload with the sheer size of the place. We were
on the hunt for Pazole. This is a soup like thing served on only the weekends.
It contains bone broth, vegetables and maiz. We searched and searched and
eventually found a place called Cocina Frida. Very tasty and flavorful!
Afterwards we exited the chaotic market and a friend bought some chicharrones
and we headed to the Zocolo area.

#+BEGIN_EXPORT html
<iframe width="100%" height="512" src="https://www.youtube.com/embed/r9ZJeezGyrU" title="Mercado Sonora" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/zJdR5qaFXFiEwD4v6"><img
src="https://lh3.googleusercontent.com/6cge64Q6X785qt4b25o0ONoQyKw7uhO-TbpV-qzYfSwpFD7s6JPaVKP__MmQjm5b93-4s5zYO-Y5h7rGED5CU-AHKM3IiFI2kEhXnVjWZaJQ_-daBcr4-KwNJZ4ZSOJh8YceekwH5itRF7Q5PotmzeMzuaHXgcn2eNLrqbkwPUFUSGLLvsSV4nmoY1C8WuSo3GlnGrP8O6eiyHXkFcGyBBWO_5W1HVJf45_GS40BNkXR_8u1jamVCqE6GU0-VarABxn0l2AN_m1mfcHy-Jsb7HJmL8-VsyrWQtuMUo4f9_WGZi4VkA6JIJYxtlAx1356d9HZYRt7fcnVzwljJk5riP3mHhMnapD_z2W4w62Yzk77V0U8qJgYXTJQQLYt3c4QpBZYu7XJ1W0QjT6hjQAZJEOPK8eKvTv0HGm7jsjTuD-lVWfwR6Y_I6jMIaAS9tQhDiAu7VJTliE-aT1n1xoSUifwUJdgDgDIbWv0B6Ls624mS6IiuK6SxAnols6bjVyDoA5xS0j0Zh5ovPaXneBIN8RX8SnVEhl14pnaHJVkf99vnHBKRKWoVWUfvkoAlp0QHkbVw-GMI0v0f0noRE-TbYkAbXiI86aivnFqknkFYbu27tjyDUMQpfipBBeKcOk3vxgjqmPe5l6sOfdlVAqd9xFpItXqczteU9cJqUoWzCAvl-mIB1Ja8r_CgJxdBNvAsutcJvt54FVIeY2sL_7PiYlQsZE7rDHKtzxFSk4QCFY3Y-Bc_9zoNhmnzBA=w1172-h879-no?authuser=0"
alt="Cocina Frida" class="inline"/></a>
#+END_EXPORT

Zocolo was the main town square with the church and main city plaza. The
architecture is incredible in the region. Here you can clearly see the
construction made from volcanic stone for the buildings. We explored some of the
buildings, walked the city streets and even visited a mercado with some famous
exotic animals and insects.

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/vU71yWiiCGfPg45A7"><img
src="https://lh3.googleusercontent.com/1-XpyeIqGBPW1401juRaXuoMNHA3VqG2ABd843hCsZ_BEmWkNE_vrgpnB8fxm3OqB6NpbSTl39FId9EzXK4FX_zVLoerjaMs0syyPwoJl5Bh-GDkziuHDT4OpbtGYYs-tyZSgIBx1CvO4Vt3Lya7-D8Sv58T_xnBviE3bHG_gBFBvMwnudOPkZeRfoAVJCrx5ElFZjckod8EehBA3X52MEri4vFVGn6PJhWxsBqs_6QYbMVUOSTn2FdHf2uzED-0PTQkDzkKr-z4wZFpApGZbLBg2I8CHCN97VntqiAUNgbUBrAhdyjacHl4s5cFjTIKlEmBq7YdQEygtZ7cvXVxN5eyzMR8xa_t_oVdN_g4oT9yH0j7yzGpNP9nAPcHoZ58cNYTzWog3GylU-x-UOvN5bLnxkHc4YBbHsc5_wOzeCxXrr6VKRFClvBC6rQJANPgx-IYWQ1-dZv0mUDcDTa_gcXXFf4mqrrFz0tcSDAMSOOV7oR5J8OLM61jyXzZDLLGIbQZ254y_q7Ev3e3WCkTW09vnvHtUQr99Qqw3EltX-HQi5NacRID0mVXJYc8QWLXZWJ_0RCEzLh5zD5V6VMsAAPa3OmQcwLX_gFrv8-a3x2GhAWEjTfm81kkB7xLWgixafM1V2AqYjb69dW2NcXzIyT9P39IRSFB9Fb2m2Ja_FpBAvsMRSXRkSp-7Ef0o7szkqIzjnYPhMrOQB4T5gKKbuZ__LbSwYLNH5FMGTxzntBUTGMIiEiGxGgv4wQ=w1172-h879-no?authuser=0"
alt="Zocolo" class="inline"/></a>
#+END_EXPORT


* Last(maybe) Day
This day was supposed to by my last for the trip but unfortunately due to a
travel agency mishap, the trip got extended. For better or worse I found myself
with an extra week in CDMX. This was also partly due to the fact that my pet
sitter was still staying in my house so I didn't really have anyplace to go back
to just yet. With these additional days left for the trip I planned with a
couple other friends who were also staying over a few more days. I ended up
losing the majority of this day to logistics and going to and from the airport.

This evening we visited the Garibaldi area, traditionally known for the
mariachi. Now many locals consider this area a tourist trap, and we were aware
ase we were continually approached by the singers on the street of the plaza.
They typically ask to sing you a song and will take payment per cancion. We
decided to skip the plaza and go straight to a restaurant that offered
legitimate mariachi bands at the table. We ordered ourselves some micheledas and
requested a few canciones like Guadalajara for the absolute genuine experience.
La authentica musica Mexicana! After this place we went to a few other clubs for
their music nights. They had performers doing the traditional rancheras like a
Antonio Aguilar and Vincent Fernandez impressions! We sang along that night and
it was a real nice, although tourist way to enjoy the night!

#+BEGIN_EXPORT html
<iframe width="100%" height="512" src="https://www.youtube.com/embed/MDBztidG6RA" title="Michelada" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/ukq3wF4JuAzwZtGd9"><img
src="https://lh3.googleusercontent.com/PDFHXaeAdLXQ4Ko9yl9nKpX1ZFF_xWXjYnuEB6UNI6dH25W-91HPQ4ANG2zWyIdWKJsOYZLX9-b81As_NVO3k-ypsdGH6B9qIKn0UJDg0nPcYri2FkUC302QAAjWXMdsHpPqtPgbhiUU0BhNz8_Vu9b-QjtL-c70zzjeOUFbN7y5vRIkTs1uxDCRnl2wH5kyN49XWmejfcH6rpZGDGfgrg9BeygJi_jqpvSvL_-z0LFl6gsOSjcrG3l3-26joovZiwMzUDtdWHKA3oGp00bMKBinVdXno4-M-xe9v0U0AGhPyHAfbaXFRZa5pUZtbp61pHpgqqj7U6HtFKRoH7gpEgE8EwL6SHQxZUJ79sZ-Cs0hnb2U5isnTcMFGtBl9Re9fRILrX3VKUnUkPkIWTvrKt7CuXKJAt9UdtOliFah9YGqjmjWDINHIa4-C0kGMYyPakldIEeyvwmJP66Sp0LOPeTzS7EK4cp1B3j_4lfRU-tPEB5uM0DL1qJYR34nJ8ATdd30BSVOudVtCkJQ7tj6w408urKj6rNz7sxF5bAKBT5SVzc4TX-_EzGiVR6lvbHd6RGZJMHiWFwasLoiTIsuwDXjcp7xKpmx_ynQBmGJzbuYRu9c_TMmCrvGUhwttD4QApM3uw4IZD70mh4WgTfV8EDT_b4xS7elLcAq0qsiCjtfqGeT2qVt_Qga5jBRu_TrfbhD9IcGQnNvbx61vC8GpiFJpPvb_BkX1ZVppGB6m3vwxhs9zlWSyAh4Yr8=w1172-h879-no?authuser=0"
alt="Mariachi" class="inline"/></a>
#+END_EXPORT


* The Rest
The remainder of the week I worked during the dag so not as much time to
explore. I found a hostel called Roomies that was a quieter place but I really
liked it because it was not a party hostel and felt more laid back there. The
lady working there was very nice and she even walked me around the city to see
the plaza monument!

I was able to fill this week by visiting the Bosque de Chapultepec, a large
castle situated on a hill in the park. This amazing palace was adorned with
murals and marble and stone work and very pleasant gardens to walk through.
Definitely a must-see in CDMX!

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/YbYmcgwzMj9PU67y5"><img
src="https://lh3.googleusercontent.com/xRAdeq_4R6MMsVD05r_8xwWAJPtzf5wb1_VHit4n82xdSc_6HhRarVleU7wSGHQ8cixMca4_S8Y5K2LyKW9rcCt6_u8cQsoNX4bBNG4GL2oI-cCCKA1C5oQ9WIAaYZpEVb8pP0ebmN2KVlVtOSC7CCX3gPiF6KA-CFwPFA6EkeVwwesXinGnbWgaz-HYLnkH4OmkrNmaoS3572wXysxQz5cWqvE3l5S7A8r-ew2us-tQPaJCPL06pJHe3yB9yVbuoewPQLuG51C4Sh52YdrEkLy_lqaLuR5jt9sqXUq51696RGDZBllA-rMrgrFSBnD_bw750PK9qkiPyi2yS9JLplXIvlB-GN981lHmbG2HUCYASI4ktBp4Hf23uP1Ucg-tiZTWDGFWyWHtgLMeTTgAW6eftd9jtvfp7_5lYKd_PZZ4ZUfyqokJJLBewU-aSnPMjZlSy_Z_MA6agFHILjXiNLi2MpeVrB9h8mqFfDY-oxbezMN3iZkLP5GPRSgfNQ0KAaHtYPWSkFGErfK-JMkWO1WLdI_ZhK6Llsn-lLrImXxahUeLgq6d0bqO2TKmMo0PphfWhJtSw0OQ32u2cJNPMWNllTdlwH675kqt4vahl1dG8aPZ0ALV5VvZINTHSf8j8uKcQrJaDorfjlzlKv-Wf_FYmapiM30rNSVyD4tDJpGRt2iQwcvtsC8Xj2rDjb_9Xy6DvRFWmmDR6e5B0OTVMb_2pEn4bEVix2WRW_Js_EYgXn8m_bbf5Lvk-Ns=w1172-h879-no?authuser=0"
alt="Chapultepec" class="inline"/></a>
#+END_EXPORT

We also visited a few very fascinating speak-easy taverns in the city that offer
drinks that are works of art themselves. The showmanship of mixing the drinks
was remarkable to watch. Clearly a talent that I never appreciated until seeing
it this moment!

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/UPqzwkeG7uyJWNy2A"><img
src="https://lh3.googleusercontent.com/pw/AL9nZEVVhtn2DpLsnvYpHrS7Yp2mfafx6LGOvUkrOuG6Q9hZQ-QEbPeZinordx33vB_wAWyouYtpkKQlI0eZqxNAs4AYiMQjFUelVFz4llgrHwOY4KvZsipHGr1roShhqBf-ugPXL9EWER56ro4MwYeV57cn=w1172-h879-no?authuser=0"
alt="" class="inline"/></a>
#+END_EXPORT

I spent the days working and sometimes visiting lunch places before returning to
work the afternoon. Of note, I visited a Columbian cafe called Pollos Mario that
had delicious pan de bono! I also visited a vegan taco place one day that had
killer pineapple and eggplant tacos!

The final tours of the trip were a Tepito tour, though a fierce district that
clearly has a way about itself! Here I was able to appreciate the core and soul
of this district with a friendly although misunderstood history. The mercado
there was massive and they are known for their exotic micheladas topped with
gummies, salts and sugar. These drinks were delicious delicacies. I had some of
my most delicious street tacos here including some liver tacos tucked away in a
stall.

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/sbtWHMyMLY15t8an9"><img
src="https://lh3.googleusercontent.com/pw/AL9nZEUkCqIBK9gcvUtqPUjXKnLHjV8qDA4TTIHUGU4cCYqKNzOUHEukbP9vjIi6NXb_26H-bhdOVkhia7lGpB_f1XS2_Wn74LkDHdT3hnudtnEBGmk91JwIfn_Dbg77Bcpn-RH8a4AzR3ydNmuVqymSiX5Q=w1172-h879-no?authuser=0"
alt="Tepito Street Food" class="inline"/></a>
#+END_EXPORT

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/UnELT27cN1MYWQYq7"><img
src="https://lh3.googleusercontent.com/MEsGH06-3ofHNb6H17we2TiFMgBwwIPQBoqzmpXAGCro14MhbPhzwArlfOZOrKZpnJlrsSTDzJafM9ml99bvdKMi5QNgnV3iSexBU0ssv8oPr1255PSs88FKWMctRUZn0KG0B4-gxwc91Ikz7lCacxApC2JrzhqHt4v7pmjaPRgB8upZbEu-RE3VRFUu7noix_LX05qM00xm32PjrChU2JbRQHhAtfSE5BM1AekF1Sqwhjw0Ip3gbaUnCHHePWevfNg9-KRYBpCp1rrhrztirR-Utsee-Rq3RSQG1RjvAP9EtN8vSlJ5ihXJQ9NxhluljI8CnJwu7ulZU6z3w5PTZqJl7bbpaCIY0aOx9UNJQmWWwFT6MoY9lVWuE2J1GWJxO8bOnXykfLvY5PCS1qtKuY88pcuig_MFzsP6ovWdAENALoWzrTDlIOmw8Gc-H_JWZSYcCwGY9xzAkB5MXr23FUvJOZQZkyc8fabCuOcRb5SBXQmsDw0UzIBID1AP1fbhgfVsWcmFf2cZi3ZFAT5ptSSeADqdRJRqbM7aI4iWIvK0j-3g8CgJyN_92AiyPLVpHVdhQtvjlr-CrpIK43JVImrg3wgr8z7ZteyFm36_aD53udom614WcQG6hAIq8DeFEsarNFk0Rj5UmexIyDKrsb8lFJcOoaPpA-0oDTVjHfo8VLsxv0iMrvQgG7c0369hgFlP5gqti-stpojwv7iwwPeF4MtqPxDdEnHpENbjirEkFm2sediPg8qe_Tc=w1172-h879-no?authuser=0"
alt="Tepito" class="inline"/></a>
#+END_EXPORT

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/qXyoaYM2PSLfo1KJA"><img
src="https://lh3.googleusercontent.com/pw/AL9nZEVuvPHE6Y3L5KCNR6-1xEN5yBTlRqerbOIuOMDtZJXlciCV7KNvCIHtTe03iYx_E_fAS63EfT59e5TK5wTL0-UlF03gEcnpFhyiRjUoWdumZ-QYYFH6n302HBs9KjkQlPgEaUOv3JCuOkHf4D6W2XUd=w1172-h879-no?authuser=0"
alt="Tepito Churros" class="inline"/></a>
#+END_EXPORT

The final day of the trip featured an amazing hike tour up the Nevado de Toluka
volcano. This is a mighty way to end my Mexico trip. The trip there was around 3
hours including transfer to collectivo. Once we reached the altitude I was
immediately hit by lack of oxygen in the air. Our guide took us slowly up for
the starter until we adjusted. We spent the time climbing until reaching a rock
scramble. The final leg before the summit featured sheer breathtaking views and
some of the most amazing vistas of my trip! After the peak, we descended down a
very unstable rock path. The gravel constantly slid out underneath us making it
a treacherous trail to keep our footing. It was absolutely as exhausting going
down as it was going up! I thoroughly recommend doing this trail if you get the
chance. All in all, around 8 hours total and we reached the city after stopping
for a nice dinner.

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/MvddvMHhVuGALmqLA"><img
src="https://lh3.googleusercontent.com/NXujLdkvfQwi1kyAtCbIVf4UAxSRcpZyCEHwjcAyFedxNATWWn-JROaxgiwRA93d2I3c8MuTMcYPPnu_QjMnGi3lDpwXnsHR4_TxdaxfwyssaS2KicVruQHRdhwTGbf1Eziu3CfRJfxHGGx8dX57RpJ5QUpS9HQ9_BajwbOXt1fL8ITKY8z1jhnK6GTS_xjzvmh3MaOL8GKIhONz7flgkPDFQhoHgcZUp-CLtRnINT9gztFMllbeyj810Q5O5V4oyL8sOwtY6jUi0_3uz-MvzGpWthAOCyWtf1SQTDn-vTwcslReB46pVZkTBxh00dUeoeO2SEdkR03R-mIFpN8E8FGGAn4r8V-dcm1wOV-W6eXjd3g6bZh5nSaTOgfIqwE3vYcCmWSBL22jLz7AaYRBfZiiwvR_UKYpVpD4G6MAKM2GRyqS6STEdlrCnLYJXoggYohVdSCxJbnXdQ-6alaOT59GU-BYwnAXaRmAD-gtJKhXadGhykjLVc2awHt55A9-do8hiP-twroE3WiS8QnPp_jnUlldA1wGMgo5nmw9q674by2G5eG_H9FDI1LNvU37NZ-PqWFGu4_RsTGdq2kpNlpKy50z7yajWLQ77xKwh8aBxY74ail1WbtuU2OCwT_9fA3vhPeJQYjPfWNqju9Z9TkJkM2OpzYjr8xl-ZI1RUS8ab4ssEEadhYSa6cjK22dQk66vqL1Xnu8kN3Pt8DUWDLYQlV50M2Ri-5N01TvTuZrEMKsfTSE4NPm-CI=w1172-h879-no?authuser=0"
alt="Nevado de Toluka" class="inline"/></a>
#+END_EXPORT

#+BEGIN_EXPORT html
<a href="https://photos.app.goo.gl/LnKtK2pbGaHU4AKHA"><img
src="https://lh3.googleusercontent.com/lAiXMUKJ7EK91i-4kjd1dgJvnnoIYuxkoRg_ZDgPnjb2krhbHA5ROIxjojUSyonxyqflcfMs2UW6knZSo-X3csGdB1CmZnJdkx1AyIyVWP_uWlVKbb5WUMSowJ5OqwggzfWOtl0dCwPKMw7VdbnEsZ1dn9LoB3I1LY_WdHNoattp3YFWRvnl23X9Wuh1nwQdDfv9SWtyb-YAVPM27mZVCkmf-sZPEM1b1vV835hRB9YoxYMUwcVPQbGB-TMJ60ZTYCNBOsF_N-q9NBxlBXanB7C6P9b8MELB7IrtdBhtwPz9PgJdX_qEZHEKFGkZ13_Oht-epvNYfHSNNpiyFeZhupodmVlr0g2kPYEjTh_iJ7TVc_c--1dTaNJktF7_Qz-VIcINsy_Zw1mhl9l4cpMaeyLwo6abv55BArJdFey5GjsrfYATeOytGM0ui6aB9oHHvw9ZaJ6YSjlx2waMCGIZu-TVyDoNmP61TPHHwuXuUP4mFuAAaWI8qFWNBLifGeZUO2Yigr930VWLXyBc_LFOmFl9BsevCdsqcLPel4UKuEVdIO0bEU4skBAt0MBSBXJeBjkvHfG5VmwwOwqtF1ZFQvgQBwGhU5PjI8iOak1SAryGmFxQR7Yv3Avh4beSJ12SiLXvov1jKHrdzAmJa6LgJR3cCej9ps1Qa4sJcbJnJm5bRL3NzSzAeeC1j6QeQQQaynv8MmoX-GANNleE6L-Yflwf6WwPYkF3oGr3dMtZH2JwzQdhGVMim7hxU3M=w1172-h879-no?authuser=0"
alt="Final Michelada" class="inline"/></a>
#+END_EXPORT


* Conclusion
This first trip to Mexico was amazing. Should you go? YES. Skip the tourist
spots in Mexico and go straight to the heart of culture and meet the people of
the region. I made some lasting connections that I hope to stay in touch with
and perhaps plan trips again to see them! This trip broke many impressions we
have of MX and I grew a lot during this trip and hope to come back soon. There
is so much more than what you hear on the news and until seeing the place for
myself, I would have lived in that same fear too. Certainly a trip I won't ever
forget!


Link to entire photo album: https://photos.app.goo.gl/YWhSFGKTFCdfd3hz9
And videos: https://www.youtube.com/watch?v=Om4eJX381oc&list=PLVXoDcbm8YOw7WKfiBtx8pKDWlLG7p_AV

[[https://bagnaram.github.io/posts/2022-08-09-mexico/][Previous Part]]
